ansible_connection: ssh

# Ubuntu 16.04 comes without Python 2, so one gets errors like "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",
# as Python 3 is already there, we´re switching over to it (see http://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#list-of-behavioral-inventory-parameters)
ansible_python_interpreter: /usr/bin/python3
