ansible_port: 2222

# By default (config.ssh.insert_key is defaulting to true, even if unset) Vagrant generates a new Keypair and places the private key
# inside .vagrant/machines/default/virtualbox/private_key & automatically copies the public key to /home/vagrant/.ssh/authorized_keys
# the path should remain stable, but if it changes, just check with `vagrant ssh-config` on commandline
ansible_ssh_private_key_file: ../../step4-windows-linux-multimachine-vagrant-docker-swarm-setup/.vagrant/machines/masterlinux/virtualbox/private_key