---
- hosts: "{{host}}"
  vars:
    base_path: "C:\\spring-boot"
    spring_boot_app:
      path: "{{base_path}}\\{{spring_boot_app_name}}"
      port: 8080
      health_url_ending: "swagger-ui.html"
    java8_update_version: 121
    java_build_version: b13
    server_jre_name: server-jre-8u{{java8_update_version}}-windows-x64.tar.gz

  tasks:
  ###### Preparation steps
  - name: Create base directory C:\spring-boot, if not there
    win_file: path={{base_path}} state=directory

  - name: Prepare Windows Docker installation
    include: prepare-docker-windows.yml

  - name: Run Spring Boot app inside Windows-Docker-Container
    include: spring-boot-app-windows-docker.yml

  - name: Healthchecking the Spring Boot app
    include: spring-boot-app-health-check.yml


