---
- hosts: "{{host}}"
  vars:
    base_path: "C:\\spring-boot"
    spring_boot_app_path: "{{base_path}}\\{{spring_boot_app_name}}"
    path_to_java_exe: "C:\\ProgramData\\Oracle\\Java\\javapath\\java.exe"

  tasks:
  ###### Preparation steps
  - name: Create base directory C:\spring-boot, if not there
    win_file: path={{base_path}} state=directory

  - name: Prepare Windows Docker installation
    include: prepare-docker-windows.yml

  - name: Run Spring Boot app inside Windows-Docker-Container
    include: spring-boot-app-windows-docker.yml


