---
- hosts: "{{host}}"
  vars:
    base_path: "C:\\spring-boot"
    service_registry_name: eureka-serviceregistry

  tasks:
  - name: Create base directory C:\spring-boot, if not there
    win_file: path={{base_path}} state=directory

  - name: Run Service Registry (Eurika Spring Boot app) inside Windows-Docker-Container
    include: spring-boot-app-windows-docker.yml
    vars:
      spring_boot_app:
        name: "{{service_registry_name}}"
        port: 8761
      jar_input_path: "../../spring-cloud-netflix-docker/{{spring_boot_app.name}}/target/{{spring_boot_app.name}}-0.0.1-SNAPSHOT.jar"

  - name: Run Reverse Proxy (Zuul Spring Boot app) inside Windows-Docker-Container
    include: spring-boot-app-windows-docker.yml
    vars:
      spring_boot_app:
        name: zuul-edgeservice
        port: 8080
      jar_input_path: "../../spring-cloud-netflix-docker/{{spring_boot_app.name}}/target/{{spring_boot_app.name}}-0.0.1-SNAPSHOT.jar"

  - name: Run Weather Backend Service (Spring Boot app) inside Windows-Docker-Container
    include: spring-boot-app-windows-docker.yml
    vars:
      spring_boot_app:
        name: weatherbackend
        port: 8090
      jar_input_path: "../../spring-cloud-netflix-docker/{{spring_boot_app.name}}/target/{{spring_boot_app.name}}-0.0.1-SNAPSHOT.jar"

  - name: Run Weather Backend Service 2 (Spring Boot app) inside Windows-Docker-Container
    include: spring-boot-app-windows-docker.yml
    vars:
      spring_boot_app:
        name: weatherbackend-second
        port: 8091
      jar_input_path: "../../spring-cloud-netflix-docker/weatherbackend/target/weatherbackend-0.0.1-SNAPSHOT.jar"

  - name: Copy docker-compose.yml to directory C:\spring-boot (this is only additionally, compose isn´t necessary for the apps to run)
    win_template:
      src: "../../spring-cloud-netflix-docker/docker-compose.yml"
      dest: "{{base_path}}\\docker-compose.yml"
