---
- hosts: all
  vars:
    masterwindows_ip: 172.16.2.12
    swarm_network_name: mixed_swarm_net

  tasks:
  - name: Checking Ansible connectivity to Windows nodes
    win_ping:
    when: inventory_hostname in groups['windows']

  - name: Checking Ansible connectivity to Linux nodes
    ping:
    when: inventory_hostname in groups['linux']

  - name: Initialize Swarm and join all Swarm nodes
    include: initialize-swarm-and-join-all-nodes.yml

  - name: Label underlying operation system to each node
    include: label-os-specific-nodes.yml

  - name: Create Swarms overlay network
    include: create-overlay-network.yml

  - name: Run Docker Swarm local Registry
    include: run-swarm-registry.yml

  - name: Run Portainer as Docker and Docker Swarm Visualizer
    include: run-portainer.yml

  - name: Obtain Docker Swarm status
    win_shell: "docker node ls"
    register: overview_result
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Swarm initialized...
    debug:
      msg:
        - "The status of the Swarm now is:"
        - "{{overview_result.stdout_lines}}"
    when: inventory_hostname == "masterwindows01"