---
- hosts: all
  vars:
    masterwindows_ip: 172.16.2.12

  tasks:
  - name: Checking Ansible connectivity to Windows nodes
    win_ping:
    when: inventory_hostname in groups['windows']

  - name: Checking Ansible connectivity to Linux nodes
    ping:
    when: inventory_hostname in groups['linux']

  - name: Open Ports in firewalls needed for Docker Swarm
    include: prepare-firewalls-for-swarm.yml

  - name: Initialize Swarm and join all Swarm nodes
    include: initialize-swarm-and-join-all-nodes.yml

  - name: Label underlying operation system to each node
    include: label-os-specific-nodes.yml

  - name: Run Docker Swarm local Registry
    include: run-swarm-registry.yml

  - name: Run Portainer as Docker and Docker Swarm Visualizer
    include: run-portainer.yml

  - name: Display the current Docker Swarm status
    include: display-swarm-status.yml