---

- hosts: all
  vars:
    masterwindows_ip: 172.16.2.12

  tasks:
  - name: Checking Ansible connectivity to Windows nodes
    win_ping:
    when: inventory_hostname in groups['windows']

  - name: Checking Ansible connectivity to Linux nodes
    ping:
    when: inventory_hostname in groups['linux']

  - name: Allow connection to Windows Manager nodes Docker Swarm port 2377
    win_shell: "netsh firewall add portopening TCP 2377 'Port 2377'"
    when: inventory_hostname in groups['masterwindows']

  - name: Leave Swarm on Windows master node, if there was a cluster before
    win_shell: "docker swarm leave --force"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Initialize Docker Swarm cluster on Windows master node
    win_shell: "docker swarm init --advertise-addr={{masterwindows_ip}} --listen-addr {{masterwindows_ip}}:2377"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Pause a few seconds after new Swarm cluster initialization to prevent later errors on obtaining tokens to early
    pause:
      seconds: 5

  - name: Obtain worker join-token from Windows master node
    win_shell: "docker swarm join-token worker -q"
    register: worker_token_result
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Obtain manager join-token from Windows master node
    win_shell: "docker swarm join-token manager -q"
    register: manager_token_result
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Syncing the worker and manager join-token results to the other hosts
    set_fact:
      worker_token_result_host_sync: "{{ hostvars['masterwindows01']['worker_token_result'] }}"
      manager_token_result_host_sync: "{{ hostvars['masterwindows01']['manager_token_result'] }}"

  - name: Extracting and saving worker and manager join-tokens in variables for joining other nodes later
    set_fact:
      worker_jointoken: "{{worker_token_result_host_sync.stdout.splitlines()[0]}}"
      manager_jointoken: "{{manager_token_result_host_sync.stdout.splitlines()[0]}}"

  - name: Join-tokens...
    debug:
      msg:
        - "The worker join-token is: '{{worker_jointoken}}'"
        - "The manager join-token is: '{{manager_jointoken}}'"

  - name: Leave Swarm on Windows worker nodes, if there was a cluster before
    win_shell: "docker swarm leave"
    ignore_errors: yes
    when: inventory_hostname in groups['workerwindows']

  - name: Add Windows worker nodes to Docker Swarm cluster
    win_shell: "docker swarm join --token {{worker_jointoken}} {{masterwindows_ip}}"
    ignore_errors: yes
    when: inventory_hostname in groups['workerwindows']

  - name: Leave Swarm on Linux worker nodes, if there was a cluster before
    shell: "docker swarm leave"
    ignore_errors: yes
    when: inventory_hostname in groups['workerlinux']

  - name: Add Linux worker nodes to Docker Swarm cluster
    shell: "docker swarm join --token {{worker_jointoken}} {{masterwindows_ip}}"
    ignore_errors: yes
    when: inventory_hostname in groups['workerlinux']

  - name: Leave Swarm on Linux manager nodes, if there was a cluster before
    shell: "docker swarm leave --force"
    ignore_errors: yes
    when: inventory_hostname in groups['masterlinux']

  - name: Add Linux manager nodes to Docker Swarm cluster
    shell: "docker swarm join --token {{manager_jointoken}} {{masterwindows_ip}}"
    ignore_errors: yes
    when: inventory_hostname in groups['masterlinux']

  - name: Label OS specific nodes for later mixed-OS deployments (masterwindows01 = windows)
    win_shell: "docker node update --label-add os=windows masterwindows01"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Label OS specific nodes for later mixed-OS deployments (workerwindows01 = windows)
    win_shell: "docker node update --label-add os=windows workerwindows01"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Label OS specific nodes for later mixed-OS deployments (workerlinux01 = linux)
    win_shell: "docker node update --label-add os=linux workerlinux01"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Label OS specific nodes for later mixed-OS deployments (masterlinux01 = linux)
    win_shell: "docker node update --label-add os=linux masterlinux01"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Create an overlay network to enable our Swarm services to connect to each other later on
    win_shell: "docker network create --driver=overlay mixed_swarm_net"
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Specify to run Docker Registry on Linux Manager node
    shell: "docker node update --label-add registry=true masterlinux01"
    ignore_errors: yes
    when: inventory_hostname == "masterlinux01"

  - name: Create directory for later volume mount into the Docker Registry service on Linux Manager node, if it doesn´t exist
    file:
      path: /mnt/registry
      state: directory
      mode: 0755
    when: inventory_hostname in groups['linux']

  - name: Run Docker Registry on Linux Manager node as Docker Swarm service
    shell: "docker service create --name swarm-registry --constraint 'node.labels.registry==true' --mount type=bind,src=/mnt/registry,dst=/var/lib/registry -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 -p 5000:5000 --replicas 1 registry:2"
    ignore_errors: yes
    when: inventory_hostname == "masterlinux01"

  - name: Obtain Docker Swarm status
    win_shell: "docker node ls"
    register: overview_result
    ignore_errors: yes
    when: inventory_hostname == "masterwindows01"

  - name: Swarm initialized...
    debug:
      msg:
        - "The status of the Swarm now is:"
        - "{{overview_result.stdout_lines}}"
    when: inventory_hostname == "masterwindows01"